version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myapp
    volumes:
        - mysql_volume:/var/lib/mysql
        - mysql_entrypoint:/docker-entrypoint-initdb.d

  app:
    image: secdevoops/spring-boot-docker:0.0.1-SNAPSHOT
    environment:
      - DB_URL_APP=jdbc:mysql://mysql:3306/myapp
      - DB_USERNAME_APP=root
      - DB_PASSWORD_APP=password
    expose:
      - 8080
      - 8000
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"

volumes:
      mysql_volume:
      mysql_entrypoint: